name: line_pattern_matcher
description: A flexible Dart package for matching complex patterns across multiple lines of text. Ideal for log analysis, text processing, and pattern recognition tasks.
version: 1.0.1
homepage: https://github.com/changyy/line_pattern_matcher_dart
repository: https://github.com/changyy/line_pattern_matcher_dart
issue_tracker: https://github.com/changyy/line_pattern_matcher_dart/issues

environment:
  sdk: '^3.5.0'

dev_dependencies:
  test: ^1.21.0

